### PR TITLE
feat: connect SOL wallet, shadcn in packages, profile page(for now), some UI updates

### PR DESCRIPTION
**Pull request by shreyas0924**
Home page : 
image

Profile page when signed in with wallet : (Phantom wallet or any other Solana compatible wallet). Then "name" over there is the wallet address
image

Profile page if not signed in
image

Profile page when sign in with github(in this case)
image

### CODE REVIEW

**Comment by TanmayDhobale** [comment]
can u make frontend more good looking

**Comment by TanmayDhobale** [comment]
> can u make frontend more good looking

for ref - https://www.lancer.so

**Comment by shreyas0924** [comment]
Yes defenitely.. This is a starting prototype, we have to make a lot of design changes

**Comment by TanmayDhobale** [comment]
> Yes defenitely.. This is a starting prototype, we have to make a lot of design changes

go for it

**Comment by shreyas0924** [comment]
can you try this out once https://github.com/shreyas0924/github-sol-auto-dispenser/tree/sol-wallet

**Comment by TanmayDhobale** [comment]
> Yes defenitely.. This is a starting prototype, we have to make a lot of design changes

design  update ?

**Comment by devsargam** [comment]
Closing in favour of #12

**Comment by shreyas0924** [comment]
#12 Isme wallet login hai hi nhi??

**Pull request closed without merging**
