### PR TITLE
Dispense solona via PR contributions #4

### PR DESCRIPTION
**Pull request by TanmayDhobale**
how the overall process works: 
1. GitHub Bot Setup:
    * We have a GitHub bot set up using the probot library, which listens to various events on the repository, such as issues being opened, PRs being opened, comments being added, and PRs being merged.
    * The bot is implemented in the gh-bot/src/app.ts file.
2. Opening an Issue or PR:
    * When a user opens an issue or a PR, the bot welcomes them with a comment and sends a notification to a Discord channel using the discord.ts file.
3. Setting a Bounty:
    * The repository owner can set a bounty for an issue by commenting with the /bounty $amount command on that issue.
    * The bot extracts the amount from the comment using the utils.ts file and saves the bounty details in the bounties.ts file.
4. Claiming the Bounty:
    * When a user opens a PR for an issue with a bounty, they can claim the bounty by commenting with the /address <solana_address> command on the PR.
    * The bot extracts the Solana address from the comment using the utils.ts file and associates it with the bounty in the bounties.ts file.
5. Transferring USDC:
    * When a PR with a claimed bounty is merged, the bot transfers the USDC tokens to the user's Solana address using the solana.ts file.
    * The bot uses the @solana/web3.js and @solana/spl-token libraries to interact with the Solana blockchain and perform the token transfer.
6. Web Application:
    * We have a Next.js web application that allows users to connect their Solana wallets using the @rainbow-me/rainbowkit library.
    * The wallet.tsx page displays the connected wallet address and provides a button to connect or disconnect the wallet.
    * The BountyList.tsx component fetches and displays a list of open bounties from the data source (currently nothing is threre we will add soon ).
    * The HistoryList.tsx component fetches and displays the history of bounty payments from the data source (same currently nothing is threre we will add soon ).
    * The solana.ts file in the web/src/utils folder provides a utility function to fetch the USDC balance of a connected wallet.

### CODE REVIEW

**Comment by nimit9** [comment]
This is great! Looking forward to contribute to this project.

**Comment by shreyas0924** [comment]
I dont think we can use ethers.js for this... We can use @solana/web3.js package for transactions.

**Comment by TanmayDhobale** [comment]
> In point 6, the first 2 subpoints are in #11

we are using https://www.rainbowkit.com to connect wallet

**Comment by shreyas0924** [comment]
> > In point 6, the first 2 subpoints are in #11
> 
> we are using https://www.rainbowkit.com to connect wallet

Rainbow kit is for EVM chains

**Comment by TanmayDhobale** [comment]
> > > In point 6, the first 2 subpoints are in #11
> > 
> > 
> > we are using https://www.rainbowkit.com to connect wallet
> 
> Rainbow kit is for EVM chains. Right?

Yes, by using  Rainbow Kit with the Solana chain and integrating it with a compatible Solana wallet (such as Phantom Wallet), you can use Rainbow Kit to process of sending bounties on the Solana blockchain.

**Comment by TanmayDhobale** [comment]
> > > In point 6, the first 2 subpoints are in #11
> > 
> > 
> > we are using https://www.rainbowkit.com to connect wallet
> 
> Rainbow kit is for EVM chains. Right?

is there any problem ?

**Comment by shreyas0924** [comment]
> > > > In point 6, the first 2 subpoints are in #11
> > > 
> > > 
> > > we are using https://www.rainbowkit.com to connect wallet
> > 
> > 
> > Rainbow kit is for EVM chains. Right?
> 
> is there any problem ?

https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180

**Comment by TanmayDhobale** [comment]
> > > > > In point 6, the first 2 subpoints are in #11
> > > > 
> > > > 
> > > > we are using https://www.rainbowkit.com to connect wallet
> > > 
> > > 
> > > Rainbow kit is for EVM chains. Right?
> > 
> > 
> > is there any problem ?
> 
> [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)

I don't know, but I think their new update solved this issue. Can you check again?

**Comment by shreyas0924** [comment]
> > > > > > In point 6, the first 2 subpoints are in #11
> > > > > 
> > > > > 
> > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > 
> > > > 
> > > > Rainbow kit is for EVM chains. Right?
> > > 
> > > 
> > > is there any problem ?
> > 
> > 
> > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> 
> I don't know, but I think their new update solved this issue. Can you check again?

https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982

Even idk if it's fixed.

**Comment by TanmayDhobale** [comment]
> > > > > > > In point 6, the first 2 subpoints are in #11
> > > > > > 
> > > > > > 
> > > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > > 
> > > > > 
> > > > > Rainbow kit is for EVM chains. Right?
> > > > 
> > > > 
> > > > is there any problem ?
> > > 
> > > 
> > > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> > 
> > 
> > I don't know, but I think their new update solved this issue. Can you check again?
> 
> [rainbow-me/rainbowkit#1327 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982)
> 
> Even idk if it's fixed.

it is

**Comment by shreyas0924** [comment]
> > > > > > > > In point 6, the first 2 subpoints are in #11
> > > > > > > 
> > > > > > > 
> > > > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > > > 
> > > > > > 
> > > > > > Rainbow kit is for EVM chains. Right?
> > > > > 
> > > > > 
> > > > > is there any problem ?
> > > > 
> > > > 
> > > > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> > > 
> > > 
> > > I don't know, but I think their new update solved this issue. Can you check again?
> > 
> > 
> > [rainbow-me/rainbowkit#1327 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982)
> > Even idk if it's fixed.
> 
> it is

Please provide source

**Comment by shreyas0924** [comment]
https://phantom-sandboxes.vercel.app/rainbowkit-sandbox

In this one, it is always connecting to ethereum testnet not solana. Wagmi doesn't support Solana

**Comment by TanmayDhobale** [comment]
> https://phantom-sandboxes.vercel.app/rainbowkit-sandbox
> 
> In this one, it is always connecting to ethereum address not solana. Wagmi doesn't support Solana

ahh make sense let`s see

**Comment by TanmayDhobale** [comment]
> > > > > > > > > In point 6, the first 2 subpoints are in #11
> > > > > > > > 
> > > > > > > > 
> > > > > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > > > > 
> > > > > > > 
> > > > > > > Rainbow kit is for EVM chains. Right?
> > > > > > 
> > > > > > 
> > > > > > is there any problem ?
> > > > > 
> > > > > 
> > > > > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> > > > 
> > > > 
> > > > I don't know, but I think their new update solved this issue. Can you check again?
> > > 
> > > 
> > > [rainbow-me/rainbowkit#1327 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982)
> > > Even idk if it's fixed.
> > 
> > 
> > it is
> 
> Please provide source

u need to see this https://www.rainbowkit.com/docs/custom-wallet-list

**Comment by shreyas0924** [comment]
> > > > > > > > > > In point 6, the first 2 subpoints are in #11
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Rainbow kit is for EVM chains. Right?
> > > > > > > 
> > > > > > > 
> > > > > > > is there any problem ?
> > > > > > 
> > > > > > 
> > > > > > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> > > > > 
> > > > > 
> > > > > I don't know, but I think their new update solved this issue. Can you check again?
> > > > 
> > > > 
> > > > [rainbow-me/rainbowkit#1327 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982)
> > > > Even idk if it's fixed.
> > > 
> > > 
> > > it is
> > 
> > 
> > Please provide source
> 
> u need to see this https://www.rainbowkit.com/docs/custom-wallet-list

You can add custom wallet. It'll still connect to EVM chains only

**Comment by TanmayDhobale** [comment]
> > > > > > > > > > > In point 6, the first 2 subpoints are in #11
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Rainbow kit is for EVM chains. Right?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > is there any problem ?
> > > > > > > 
> > > > > > > 
> > > > > > > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> > > > > > 
> > > > > > 
> > > > > > I don't know, but I think their new update solved this issue. Can you check again?
> > > > > 
> > > > > 
> > > > > [rainbow-me/rainbowkit#1327 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982)
> > > > > Even idk if it's fixed.
> > > > 
> > > > 
> > > > it is
> > > 
> > > 
> > > Please provide source
> > 
> > 
> > u need to see this https://www.rainbowkit.com/docs/custom-wallet-list
> 
> You can add custom wallet. It'll still connect to EVM chains only

any other option u know ?

**Comment by shreyas0924** [comment]
> > > > > > > > > > > > In point 6, the first 2 subpoints are in #11
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > we are using https://www.rainbowkit.com to connect wallet
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Rainbow kit is for EVM chains. Right?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > is there any problem ?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [rainbow-me/rainbowkit#344 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/344#discussioncomment-2718180)
> > > > > > > 
> > > > > > > 
> > > > > > > I don't know, but I think their new update solved this issue. Can you check again?
> > > > > > 
> > > > > > 
> > > > > > [rainbow-me/rainbowkit#1327 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/1327#discussioncomment-6560982)
> > > > > > Even idk if it's fixed.
> > > > > 
> > > > > 
> > > > > it is
> > > > 
> > > > 
> > > > Please provide source
> > > 
> > > 
> > > u need to see this https://www.rainbowkit.com/docs/custom-wallet-list
> > 
> > 
> > You can add custom wallet. It'll still connect to EVM chains only
> 
> any other option u know ?

solana wallet adapter with next-auth. I've done the same thing in this PR #11

**Comment by devsargam** [comment]
Closing in favour of #12

**Pull request closed without merging**
